"""
Embedded images.
Generated by image_generator.py
"""

from wx.lib.embeddedimage import PyEmbeddedImage


data_table_24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADhklEQVRIiY2VsWtbZ'
    b'xTFf+fxMMIIkUGEYrKJDJ2KVBoIxRjyJ5hgDHp0aSFDxwwhhCK/wYTiIW0IpUNHZU9NlhJMCaFDQ7H+hQwmziSEUYUJ5p'
    b'0O332SYjuh36JP55333ffOPfc8dfvl7xK3bIOEiGVjCTAyi30wDHPuR/f261xwA9NAOhJUQWkhtYEx1sSJnUm6lg7xEVZ'
    b'lQHJLqI0ZW0xksqhwTdKN9Ee8BT7HdGx1gIFthHcRHaCD9AXwBvxO6EtBR9CxeQCA+FFwPfjXDW8w5PFECJ0dPh0A0CtK'
    b'JLBhtIQZQ1KSJW5lG0kcDgdVqFN1+zsVigJYmPNLSBeQhcDLuITt81iFQb1+eYxYAXaBpCteBzax9i3+TM2lAboLzrH2L'
    b'GapKDeNt2SeIx3UZQT3gVV1+zvHEp/N22+RbHPxSev1vxyU9tNcSYcxosRUiaENi9vCzwwHqZgaEveibw+BGUn7rw3bgn'
    b'3gRTrdID0AmnkUnBp+GT0dnEFqHPZtpFej4eAJQK9ftgx3gIbgt8PhYBz4qeRto79qLkC3KL8HmnkasJBmSQPBh41TuqB'
    b'k/g/xy+SMe2uJMuMrvaI8i8uraWbd6BXllajZFMoQmU2rW5SVaq4StxvcqJkBqFeUx0Db5iilgUFq2m5LGts+SW0hA62F'
    b'59+Cw/NqgmOSdbIwvNaA9znLGVS/vp3VKszTyYC8UMdzQhbzl8lzLUFJ4jzueIf4yuYstUPfAXvAI4knSxK9dGryBvIEh'
    b'O1vJP0s+zHiUW1Qw9+S1vJ4gQozqV3U7e/MkiyaHQ4HE4Bev6wQlXBldDIa7iS8KGch2781N/AKTCacMmZpSZdHwsem73'
    b'IjOakfTV4BlzZnUWDDsCV4hv0iqjaAe8F9iJkGvg5sA/vgP+pKln4QNNXtlykqmKdq+p373YvmL+1TnH96D57myVYaA7u'
    b'gKgZkHbGJSWGXFGtg7iJyYE/SLLS4Kdgyeg4caDGE921WcyQMU8Hj0TCaXJTvDZsSL0fDnZ8Ca0n6Nlz06zwqinKKtIX9'
    b'quYGfkfSaman8CQmLwlodD7fXTf0vCWS33X+4wEZmDxuyISyXlFmQFW74OL6tIt6RZkOtsHOzFJUAEeGKsitwMbApM4WQ'
    b'Xz0OWKJq+A6uEBmuCY4zW2/lnQLaNdxEW87NawIri497GmSg7apYwsMU8yKxFUvzjg1+uc/ZgfVB14qAJYAAAAASUVORK'
    b'5CYII='
)
