""""
Generate embedded images in a module ready for import.

Image source:
https://www.iconsdb.com
Color: #325c81
Tree: 16px
Toolbar: 24px

image name        : icon name
configuration     : settings 4
data table        : grid
graph             : use graphs, remove bottom line, center top line
graphs            : line
instrument        : chip 2 (make it solid, and add pin 1 mark from processor)
instruments       : processor
measurement       : speedometer (remove small bar)
new configuration : file
open              : folder 3
process           : network
refresh           : refresh
restore layout    : combine undo 4 with window layout
save              : save
settings          : settings 12
start             : play
step              : arrow right 3
stop              : stop
switch            : switch 3
time              : time

"""

import base64
import os
import pathlib
import wx


MAX_LINE_LENGTH = 93
EXTENSIONS = [".png"]


def generate_images():
    path = os.path.dirname(os.path.abspath(__file__))
    output_filename = os.path.join(path, "images.py")
    search_path = os.path.join(path, "artifacts")
    items = [p for p in pathlib.Path(search_path).iterdir() if p.suffix.lower() in EXTENSIONS]
    output = '"""\n'
    output += "Embedded images.\n"
    output += "Generated by image_generator.py\n"
    output += '"""\n\n'
    output += "from wx.lib.embeddedimage import PyEmbeddedImage\n\n\n"

    for item in items:
        with open(item, "rb") as fp:
            data = base64.b64encode(fp.read())

        bname = os.path.basename(item)
        var_name = os.path.splitext(bname)[0].replace("-", "_").replace(" ", "_")
        output += f"{var_name} = PyEmbeddedImage(\n"

        while len(data) > MAX_LINE_LENGTH:
            line = data[:MAX_LINE_LENGTH]
            data = data[MAX_LINE_LENGTH:]
            output += f"    {line}\n"
        if len(data) > 0:
            output += f"    {data}\n"
        output += ")\n\n"

    with open(output_filename, "w", encoding="utf-8") as fp:
        fp.write(output.strip("\n") + "\n")

def test_generated_images():
    # We cannot put this import at the top.
    # If the file not yet exists, the generation will fail.
    # And to make sure we have the generated version, we need to import after generation.
    # pylint: disable=import-outside-toplevel
    import src.models.images as Images

    app = wx.App(False)
    f = wx.Dialog(None, title="Images test")
    f.SetInitialSize((300, 200))
    panel = wx.Panel(f)
    box = wx.BoxSizer(wx.VERTICAL)
    panel.SetSizer(box)
    f.Show()

    i = 0
    max_per_row = 10
    sizer = None
    for attr in dir(Images):
        image = getattr(Images, attr)
        if isinstance(image, wx.lib.embeddedimage.PyEmbeddedImage):
            bmp = image.GetBitmap()
            static_bitmap = wx.StaticBitmap(panel, bitmap=bmp)
            if i == 0:
                sizer = wx.BoxSizer(wx.HORIZONTAL)
            sizer.Add(static_bitmap, 0, wx.ALL, 2)
            i += 1
            if i == max_per_row:
                box.Add(sizer, 0, wx.ALL, 2)
                sizer = wx.BoxSizer(wx.HORIZONTAL)
                i = 0
    if i > 0:
        box.Add(sizer, 0, wx.ALL, 2)
    box.Layout()

    app.MainLoop()


if __name__ == "__main__":

    generate_images()
    test_generated_images()
