name: Windows test and build

on:
  push:

jobs:
  test:
    runs-on: windows-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Setup windows environment
        uses: ./.github/actions/windows_setup
      
      - name: Run tests
        shell: pwsh
        run: |
          python tests/run_all_unit_tests.py
      
      - name: Upload test report artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: TestRunnerReport-${{ github.run_id }}
          path: tests/test_reports/
          retention-days: 30
  
  build:
    runs-on: windows-latest
    needs: test
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Setup windows environment
        uses: ./.github/actions/windows_setup
      
      - name: Build
        shell: pwsh
        run: |
          python build/create_deployment.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: BuildOutput-${{ github.run_id }}
          path: build/build_output/dist/LilyDataLoggerStudio/
          retention-days: 30
  
